platform: linux
image_resource:
  { type: docker-image, source: { repository: vcpici/vcpi-main } }

inputs:
  - name: source-ci
  - name: director-state-v65
  - name: director-env-v65
  - name: director-creds-v65
  - name: director-config-v65
  - name: environment

run:
  path: source-ci/ci/tasks/teardown.sh
